---
services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"        # SMTP port
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025" # Web UI
